/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package massalud.Vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import massalud.AccesoDatos.Conexion;
import massalud.AccesoDatos.EmpleadoData;
import massalud.Entidades.Empleado;

/**
 *
 * @author Cintia
 */
public class Login extends javax.swing.JFrame {
    Connection con=null;
//private EmpleadoData empData= new EmpleadoData();
  /**
   * Creates new form Login
   */
  public Login() {
    initComponents();
    setIconImage(new ImageIcon(getClass().getResource("/massalud/Recursos/icon.jpeg")).getImage());
    setLocationRelativeTo(null);
//    setIconImage(new ImageIcon(getClass().getResource("/massalud/Recursos/icon.jpeg")).getImage());
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        ImageIcon icono=new ImageIcon(getClass().getResource("/massalud/Recursos/f1.jpg"));
        Image imagen=icono.getImage();
        PanelLog = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            }
        };
        texemp = new javax.swing.JTextField();
        Emp = new javax.swing.JLabel();
        contra = new javax.swing.JLabel();
        texcontra = new javax.swing.JPasswordField();
        botonin = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLog.setBackground(new java.awt.Color(62, 67, 76));
        PanelLog.setPreferredSize(new java.awt.Dimension(850, 650));
        PanelLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texemp.setBackground(new java.awt.Color(204, 204, 204));
        texemp.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        texemp.setForeground(new java.awt.Color(51, 51, 51));
        texemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texempActionPerformed(evt);
            }
        });
        PanelLog.add(texemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 240, 40));

        Emp.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Emp.setForeground(new java.awt.Color(102, 102, 102));
        Emp.setText("Usuario");
        PanelLog.add(Emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 90, 40));

        contra.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        contra.setForeground(new java.awt.Color(102, 102, 102));
        contra.setText("Contraseña");
        PanelLog.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, 40));

        texcontra.setBackground(new java.awt.Color(204, 204, 204));
        texcontra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texcontra.setForeground(new java.awt.Color(51, 51, 51));
        texcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texcontraActionPerformed(evt);
            }
        });
        texcontra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                texcontraKeyPressed(evt);
            }
        });
        PanelLog.add(texcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 240, 40));

        botonin.setBackground(new java.awt.Color(102, 102, 102));
        botonin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        botonin.setForeground(new java.awt.Color(204, 255, 204));
        botonin.setText("INGRESAR");
        botonin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninActionPerformed(evt);
            }
        });
        botonin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botoninKeyPressed(evt);
            }
        });
        PanelLog.add(botonin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 160, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/logo.gif"))); // NOI18N
        PanelLog.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 344, 315));

        getContentPane().add(PanelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void texempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texempActionPerformed
    // TODO add your handling code here:
    
    
  }//GEN-LAST:event_texempActionPerformed

  private void texcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texcontraActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_texcontraActionPerformed

  private void botoninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninActionPerformed
    // TODO add your handling code here:
    Login();
  }//GEN-LAST:event_botoninActionPerformed

  private void botoninKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botoninKeyPressed
    // TODO add your handling code here:

   
  }//GEN-LAST:event_botoninKeyPressed

  private void texcontraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texcontraKeyPressed
    // TODO add your handling code here:
     if (evt.getKeyCode()==KeyEvent.VK_ENTER){
    Login();
    }
  }//GEN-LAST:event_texcontraKeyPressed

  /**
   * @param args the command line arguments
   */
  
  public void Login(){
      con=Conexion.getConexion();
    String usuario=null;
    String contra=null;
     String contra1=(String) texcontra.getText();
    String sql="select nombre, usuario, contraseña from empleado where estado=1";
        try {
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            
            while (rs.next()) {
                usuario = rs.getString("usuario");
                contra = rs.getString("contraseña");
                if (usuario.equalsIgnoreCase(texemp.getText()) && contra.equalsIgnoreCase(contra1)) {
                    String nombre="Bienvenido a Mas Salud!! "+rs.getString("nombre");
                    ImageIcon icono=new ImageIcon("/massalud/Recursos/Icob.png");
                     JOptionPane.showMessageDialog(this, nombre, "Ingreso Exitoso ",JOptionPane.PLAIN_MESSAGE,icono);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    this.dispose();
                   
                    break;
                }
            
            }
            if(!usuario.equalsIgnoreCase(texemp.getText()) || !contra.equalsIgnoreCase(contra1)){
                texemp.setText("");
                texcontra.setText("");
                JOptionPane.showMessageDialog(this,"Contraseña y/o Usuario incorrectos, Ingrese Nuevamente");
            }
            
//    if (usuario.equals("Leon")&& contra.compareTo("123456")==0){
//    Menu menu=new Menu();
//    menu.setVisible(true);
//    this.dispose();
//    }else{
//      JOptionPane.showMessageDialog(null,"Verifique Usuario y/o Contraseña","Error",JOptionPane.WARNING_MESSAGE);
//    }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
  }
  
  
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Login().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Emp;
    private javax.swing.JPanel PanelLog;
    private javax.swing.JButton botonin;
    private javax.swing.JLabel contra;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField texcontra;
    private javax.swing.JTextField texemp;
    // End of variables declaration//GEN-END:variables
public Icon icono(){
    ImageIcon imagen=new ImageIcon("/massalud/Recursos/iconoBienvenidochico.jpg");
    return imagen;
}

}
