/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package massalud.Vistas;

import static com.sun.org.apache.xpath.internal.axes.HasPositionalPredChecker.check;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import massalud.AccesoDatos.Conexion;
import massalud.AccesoDatos.EmpleadoData;
import massalud.Entidades.Empleado;

/**
 *
 * @author Cintia
 */
public class Login extends javax.swing.JFrame {

  Connection con = null;
private EmpleadoData empData= new EmpleadoData();

  /**
   * Creates new form Login
   */
  public Login() {
    initComponents();
    
    this.VistaC.setVisible(false);
    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    setIconImage(new ImageIcon(getClass().getResource("/massalud/Recursos/icon.png")).getImage());
    setLocationRelativeTo(null);

  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel3 = new javax.swing.JLabel();
    ImageIcon icono=new ImageIcon(getClass().getResource("/massalud/Recursos/fini.png"));
    Image imagen=icono.getImage();
    PanelLog = new javax.swing.JPanel(){
      public void paintComponent(Graphics g){
        g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
      }
    };
    texemp = new javax.swing.JTextField();
    Emp = new javax.swing.JLabel();
    contra = new javax.swing.JLabel();
    texcontra = new javax.swing.JPasswordField();
    botonin = new javax.swing.JButton();
    VistaO = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    VistaC = new javax.swing.JLabel();
    VerPass = new javax.swing.JCheckBox();
    jLabel2 = new javax.swing.JLabel();

    jLabel3.setText("jLabel3");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    PanelLog.setBackground(new java.awt.Color(62, 67, 76));
    PanelLog.setPreferredSize(new java.awt.Dimension(850, 650));
    PanelLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    texemp.setBackground(new java.awt.Color(255, 255, 255));
    texemp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    texemp.setForeground(new java.awt.Color(0, 153, 153));
    texemp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        texempActionPerformed(evt);
      }
    });
    PanelLog.add(texemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 200, 40));

    Emp.setFont(new java.awt.Font("Segoe UI Black", 1, 26)); // NOI18N
    Emp.setForeground(new java.awt.Color(0, 153, 153));
    Emp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Emp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/usu1.png"))); // NOI18N
    Emp.setText("Usuario");
    PanelLog.add(Emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 160, 60));

    contra.setFont(new java.awt.Font("Segoe UI Black", 1, 26)); // NOI18N
    contra.setForeground(new java.awt.Color(0, 153, 153));
    contra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/contra2.png"))); // NOI18N
    contra.setText("Contraseña");
    PanelLog.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 220, 60));

    texcontra.setBackground(new java.awt.Color(255, 255, 255));
    texcontra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    texcontra.setForeground(new java.awt.Color(0, 153, 153));
    texcontra.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        texcontraActionPerformed(evt);
      }
    });
    texcontra.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        texcontraKeyPressed(evt);
      }
    });
    PanelLog.add(texcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 200, 40));

    botonin.setBackground(new java.awt.Color(0, 153, 153));
    botonin.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
    botonin.setForeground(new java.awt.Color(0, 153, 153));
    botonin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/Ingresarc.png"))); // NOI18N
    botonin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botoninActionPerformed(evt);
      }
    });
    botonin.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        botoninKeyPressed(evt);
      }
    });
    PanelLog.add(botonin, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 160, 50));

    VistaO.setForeground(new java.awt.Color(0, 153, 153));
    VistaO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/Cin icono4a.png"))); // NOI18N
    VistaO.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        VistaOMousePressed(evt);
      }
    });
    PanelLog.add(VistaO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 340, -1, -1));

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/logoini.gif"))); // NOI18N
    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    PanelLog.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 520, 530));

    VistaC.setForeground(new java.awt.Color(255, 153, 0));
    VistaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/Cin icono3a.png"))); // NOI18N
    VistaC.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        VistaCMousePressed(evt);
      }
    });
    PanelLog.add(VistaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 340, 40, 40));

    VerPass.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
    VerPass.setForeground(new java.awt.Color(0, 153, 153));
    VerPass.setText("Ver contraseña");
    VerPass.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        VerPassActionPerformed(evt);
      }
    });
    PanelLog.add(VerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, 160, -1));

    jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(204, 102, 0));
    jLabel2.setText("© Creado y Diseñado |G17~CDJL|");
    PanelLog.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 690, 250, -1));

    getContentPane().add(PanelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 780));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void texempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texempActionPerformed
    // TODO add your handling code here:


  }//GEN-LAST:event_texempActionPerformed

  private void texcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texcontraActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_texcontraActionPerformed

  private void botoninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninActionPerformed
    // TODO add your handling code here:
//if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
    Login();
//    }
  }//GEN-LAST:event_botoninActionPerformed

  private void botoninKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botoninKeyPressed
    // TODO add your handling code here:

  }//GEN-LAST:event_botoninKeyPressed

  private void texcontraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texcontraKeyPressed
    // TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      Login();
    }
  }//GEN-LAST:event_texcontraKeyPressed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    // TODO add your handling code here:
     Object[] opciones = {"Si", "NO"};
    String nombre = "¿Está saliendo de MAS SALUD?";
    UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 18));
    UIManager.put("OptionPane.messageForeground", new Color(204, 102, 0));
// UIManager.put("OptionPane.buttonFont", new Font("Segoe UI", Font.BOLD, 16));
//    UIManager.put("OptionPane.buttonForeground", new Color(204, 204, 0));
    ImageIcon icono = new ImageIcon(getClass().getResource("/massalud/Recursos/icob.png"));
    int seleccion = JOptionPane.showOptionDialog(this, nombre, "Salir ", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, icono, opciones, opciones[1]);

    if (seleccion == JOptionPane.YES_OPTION) {
      this.dispose();
    } else {
    }
  }//GEN-LAST:event_formWindowClosing

  private void VerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPassActionPerformed
    // TODO add your handling code here:
    if(VerPass.isSelected()){
    texcontra.setEchoChar((char)0);
    }
    else{
     texcontra.setEchoChar('*');
    }
    
  }//GEN-LAST:event_VerPassActionPerformed

  private void VistaOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VistaOMousePressed
    // TODO add your handling code here:
    VistaO.setVisible(false);
       VistaC.setVisible(true);
  texcontra.setEchoChar((char)0);
    
  }//GEN-LAST:event_VistaOMousePressed

  private void VistaCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VistaCMousePressed
    // TODO add your handling code here:
     VistaC.setVisible(false);
       VistaO.setVisible(true);
 texcontra.setEchoChar('*');
  }//GEN-LAST:event_VistaCMousePressed

  /**
   * @param args the command line arguments
   */
  public void Login() {
con = Conexion.getConexion();
String usuario = null;
String contra = null;
String contra1 = (String) texcontra.getText();
String sql = "select nombre, usuario, contraseña,idEmpleado from empleado where estado=1";
boolean usuarioValido = false;
boolean contraseñaValida = false;

try {
  PreparedStatement ps = con.prepareStatement(sql);
  ResultSet rs = ps.executeQuery();

  while (rs.next()) {
    usuario = rs.getString("usuario");
    contra = rs.getString("contraseña");
    
    if (usuario.equalsIgnoreCase(texemp.getText()) && contra.equals(contra1)) {
      usuarioValido = true;
      contraseñaValida = true;
      String nombre = "Bienvenido a Mas Salud!!! " + rs.getString("nombre");
      UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 18));
      UIManager.put("OptionPane.messageForeground", new Color(204, 102, 0));
      ImageIcon icono = new ImageIcon(getClass().getResource("/massalud/Recursos/icob.png"));
      JOptionPane.showMessageDialog(this, nombre, "  Ingreso Exitoso ", JOptionPane.PLAIN_MESSAGE, icono);
      Menu menu = new Menu();
      menu.setVisible(true);
      this.dispose();
      break;
    } else if (usuario.equalsIgnoreCase(texemp.getText())) {
      usuarioValido = true;
    } else if (contra.equals(contra1)) {
      contraseñaValida = true;
    }
  }
  if (!usuarioValido && !contraseñaValida) {
    texemp.setText("");
    texcontra.setText("");
    String nombre = "Usuario y contraseña incorrectos. Por favor, ingrese nuevamente.";                
    UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 15));          
    UIManager.put("OptionPane.messageForeground", new Color(204, 102, 0));
    ImageIcon icono = new ImageIcon(getClass().getResource("/massalud/Recursos/icob.png"));
    JOptionPane.showMessageDialog(this, nombre, "Ingreso Fallido", JOptionPane.ERROR_MESSAGE,icono);
  } else if (!usuarioValido) {
    texemp.setText("");
    String nombre = "Usuario incorrecto. Por favor, ingrese nuevamente.";                
    UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 15));          
    UIManager.put("OptionPane.messageForeground", new Color(204, 102, 0));
    ImageIcon icono = new ImageIcon(getClass().getResource("/massalud/Recursos/icob.png"));
    JOptionPane.showMessageDialog(this, nombre, "Ingreso Fallido", JOptionPane.ERROR_MESSAGE,icono);
  } else if (!contraseñaValida) {
    texcontra.setText("");
    String nombre = "Contraseña incorrecta. Por favor, ingrese nuevamente.";                
    UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 15));          
    UIManager.put("OptionPane.messageForeground", new Color(204, 102, 0));
    ImageIcon icono = new ImageIcon(getClass().getResource("/massalud/Recursos/icob.png"));
    JOptionPane.showMessageDialog(this, nombre, "Ingreso Fallido", JOptionPane.ERROR_MESSAGE,icono);
  }
} catch (SQLException ex) {
 
  String mensaje = "Error de base de datos: " + ex.getMessage();
  UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 18));          
  UIManager.put("OptionPane.messageForeground", new Color(204, 102, 0));
  ImageIcon icono = new ImageIcon(getClass().getResource("/massalud/Recursos/icob.png"));
  JOptionPane.showMessageDialog(this, mensaje, "Error de Base de Datos", JOptionPane.ERROR_MESSAGE,icono);
  Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
}
  }
  public int obtenerId(int Id){
   int Idempleado=Id;
   return Idempleado;
    
    
  }
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Login().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Emp;
  private javax.swing.JPanel PanelLog;
  private javax.swing.JCheckBox VerPass;
  private javax.swing.JLabel VistaC;
  private javax.swing.JLabel VistaO;
  private javax.swing.JButton botonin;
  private javax.swing.JLabel contra;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPasswordField texcontra;
  private javax.swing.JTextField texemp;
  // End of variables declaration//GEN-END:variables
public Icon icono() {
    ImageIcon imagen = new ImageIcon("/massalud/Recursos/iconoBienvenidochico.jpg");
    return imagen;
  }

}
