/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package massalud.Vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JCheckBox;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import massalud.AccesoDatos.AfiliadoData;
import massalud.Entidades.Afiliado;

/**
 *
 * @author Cintia
 */
public class Menu extends javax.swing.JFrame {

  private AfiliadoData afiData = new AfiliadoData();

  private Afiliado afiliadoActualDni = null;

  /**
   * Creates new form Menu
   */
  public Menu() {
    initComponents();
    setIconImage(new ImageIcon(getClass().getResource("/massalud/Recursos/icon.png")).getImage());
    setLocationRelativeTo(null);

    POrden.setBackground(new Color(204, 102, 0));
    Orden.setForeground(new Color(0, 204, 204));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jDesktopPane1 = new javax.swing.JDesktopPane();
    ImageIcon icono2=new ImageIcon(getClass().getResource("/massalud/Recursos/f2.png"));
    Image imagen2=icono2.getImage();
    PanelMenu = new javax.swing.JPanel(){
      public void paintComponent(Graphics g){
        g.drawImage(imagen2,0,0,getWidth(),getHeight(),this);
      }
    };
    logomenu = new javax.swing.JLabel();
    POrden = new javax.swing.JPanel();
    Orden = new javax.swing.JLabel();
    PAfil = new javax.swing.JPanel();
    Afil = new javax.swing.JLabel();
    PPrest = new javax.swing.JPanel();
    Prest = new javax.swing.JLabel();
    PEspe = new javax.swing.JPanel();
    Espe = new javax.swing.JLabel();
    PEmpl = new javax.swing.JPanel();
    Empl = new javax.swing.JLabel();
    PanelOt = new javax.swing.JPanel();
    ImageIcon icono=new ImageIcon(getClass().getResource("/massalud/Recursos/F1.png"));
    Image imagen=icono.getImage();
    FOrd = new javax.swing.JPanel(){
      public void paintComponent(Graphics g){
        g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
      }
    };
    Ordenes = new javax.swing.JLabel();
    Docu = new javax.swing.JLabel();
    Doc = new javax.swing.JTextField();
    IdAfil = new javax.swing.JLabel();
    IdAf = new javax.swing.JTextField();
    Nomb = new javax.swing.JLabel();
    Nom = new javax.swing.JTextField();
    Apel = new javax.swing.JLabel();
    Ape = new javax.swing.JTextField();
    Domi = new javax.swing.JLabel();
    Dom = new javax.swing.JTextField();
    Telf = new javax.swing.JLabel();
    Ina = new java.awt.Checkbox();
    Act = new java.awt.Checkbox();
    Corre1 = new javax.swing.JLabel();
    Tel = new javax.swing.JTextField();
    Buscar = new javax.swing.JButton();
    ImageIcon iconoa=new ImageIcon(getClass().getResource("/massalud/Recursos/F1.png"));
    Image imagena=iconoa.getImage();
    FAfi = new javax.swing.JPanel(){
      public void paintComponent(Graphics g){
        g.drawImage(imagena,0,0,getWidth(),getHeight(),this);
      }
    };
    afili = new javax.swing.JLabel();
    ImageIcon iconop=new ImageIcon(getClass().getResource("/massalud/Recursos/F1.png"));
    Image imagenp=iconop.getImage();
    FPres = new javax.swing.JPanel(){
      public void paintComponent(Graphics g){
        g.drawImage(imagenp,0,0,getWidth(),getHeight(),this);
      }
    }
    ;
    prest = new javax.swing.JLabel();
    ImageIcon iconoe=new ImageIcon(getClass().getResource("/massalud/Recursos/F1.png"));
    Image imagene=iconoe.getImage();
    FEsp = new javax.swing.JPanel(){

      public void paintComponent(Graphics g){
        g.drawImage(imagene,0,0,getWidth(),getHeight(),this);
      }
    };
    espe = new javax.swing.JLabel();
    ImageIcon iconoem=new ImageIcon(getClass().getResource("/massalud/Recursos/F1.png"));
    Image imagenem=iconoem.getImage();
    FEmp = new javax.swing.JPanel(){

      public void paintComponent(Graphics g){
        g.drawImage(imagenem,0,0,getWidth(),getHeight(),this);
      }
    };
    jLabel6 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    logomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/logmenu.gif"))); // NOI18N

    POrden.setBackground(new java.awt.Color(0, 204, 204));
    POrden.setPreferredSize(new java.awt.Dimension(280, 50));
    POrden.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        POrdenMouseClicked(evt);
      }
    });

    Orden.setFont(new java.awt.Font("Bauhaus 93", 0, 22)); // NOI18N
    Orden.setForeground(new java.awt.Color(204, 102, 0));
    Orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/orden.png"))); // NOI18N
    Orden.setLabelFor(Ape);
    Orden.setText("Ordenes");
    Orden.setAlignmentY(0.0F);

    javax.swing.GroupLayout POrdenLayout = new javax.swing.GroupLayout(POrden);
    POrden.setLayout(POrdenLayout);
    POrdenLayout.setHorizontalGroup(
      POrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(POrdenLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Orden, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    POrdenLayout.setVerticalGroup(
      POrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POrdenLayout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addComponent(Orden, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE))
    );

    PAfil.setBackground(new java.awt.Color(0, 204, 204));
    PAfil.setPreferredSize(new java.awt.Dimension(280, 50));
    PAfil.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        PAfilMouseClicked(evt);
      }
    });

    Afil.setFont(new java.awt.Font("Bauhaus 93", 0, 22)); // NOI18N
    Afil.setForeground(new java.awt.Color(204, 102, 0));
    Afil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/Afiliados.png"))); // NOI18N
    Afil.setText("Afiliados");

    javax.swing.GroupLayout PAfilLayout = new javax.swing.GroupLayout(PAfil);
    PAfil.setLayout(PAfilLayout);
    PAfilLayout.setHorizontalGroup(
      PAfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PAfilLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Afil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(27, Short.MAX_VALUE))
    );
    PAfilLayout.setVerticalGroup(
      PAfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAfilLayout.createSequentialGroup()
        .addGap(0, 1, Short.MAX_VALUE)
        .addComponent(Afil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    PPrest.setBackground(new java.awt.Color(0, 204, 204));
    PPrest.setForeground(new java.awt.Color(51, 51, 255));
    PPrest.setPreferredSize(new java.awt.Dimension(280, 50));
    PPrest.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        PPrestMouseClicked(evt);
      }
    });

    Prest.setFont(new java.awt.Font("Bauhaus 93", 0, 22)); // NOI18N
    Prest.setForeground(new java.awt.Color(204, 102, 0));
    Prest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/Prestador.png"))); // NOI18N
    Prest.setText("Prestador");

    javax.swing.GroupLayout PPrestLayout = new javax.swing.GroupLayout(PPrest);
    PPrest.setLayout(PPrestLayout);
    PPrestLayout.setHorizontalGroup(
      PPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PPrestLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Prest)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    PPrestLayout.setVerticalGroup(
      PPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Prest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
    );

    PEspe.setBackground(new java.awt.Color(0, 204, 204));
    PEspe.setForeground(new java.awt.Color(51, 102, 255));
    PEspe.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        PEspeMouseClicked(evt);
      }
    });

    Espe.setFont(new java.awt.Font("Bauhaus 93", 0, 22)); // NOI18N
    Espe.setForeground(new java.awt.Color(204, 102, 0));
    Espe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/Especialidad.png"))); // NOI18N
    Espe.setText("Especialidad");

    javax.swing.GroupLayout PEspeLayout = new javax.swing.GroupLayout(PEspe);
    PEspe.setLayout(PEspeLayout);
    PEspeLayout.setHorizontalGroup(
      PEspeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PEspeLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Espe, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(15, Short.MAX_VALUE))
    );
    PEspeLayout.setVerticalGroup(
      PEspeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Espe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    PEmpl.setBackground(new java.awt.Color(0, 204, 204));
    PEmpl.setForeground(new java.awt.Color(51, 102, 255));
    PEmpl.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        PEmplMouseClicked(evt);
      }
    });

    Empl.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
    Empl.setForeground(new java.awt.Color(204, 102, 0));
    Empl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/Empleados.png"))); // NOI18N
    Empl.setText("Empleados");
    Empl.setAlignmentY(0.0F);

    javax.swing.GroupLayout PEmplLayout = new javax.swing.GroupLayout(PEmpl);
    PEmpl.setLayout(PEmplLayout);
    PEmplLayout.setHorizontalGroup(
      PEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PEmplLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Empl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    PEmplLayout.setVerticalGroup(
      PEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PEmplLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(Empl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
    PanelMenu.setLayout(PanelMenuLayout);
    PanelMenuLayout.setHorizontalGroup(
      PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PanelMenuLayout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(logomenu, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(POrden, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(PEmpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PEspe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PAfil, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(PPrest, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
        .addContainerGap(13, Short.MAX_VALUE))
    );
    PanelMenuLayout.setVerticalGroup(
      PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PanelMenuLayout.createSequentialGroup()
        .addGap(51, 51, 51)
        .addComponent(logomenu, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(145, 145, 145)
        .addComponent(POrden, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(PAfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(PPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(PEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(PEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(77, Short.MAX_VALUE))
    );

    jDesktopPane1.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 260, 780));

    PanelOt.setBackground(new java.awt.Color(204, 255, 204));
    PanelOt.setLayout(new javax.swing.OverlayLayout(PanelOt));

    FOrd.setPreferredSize(new java.awt.Dimension(870, 780));

    Ordenes.setFont(new java.awt.Font("Bauhaus 93", 3, 26)); // NOI18N
    Ordenes.setForeground(new java.awt.Color(0, 102, 204));
    Ordenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/ord (2).png"))); // NOI18N

    Docu.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
    Docu.setForeground(new java.awt.Color(0, 153, 153));
    Docu.setText("DNI:");

    Doc.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DocActionPerformed(evt);
      }
    });

    IdAfil.setFont(new java.awt.Font("Bauhaus 93", 0, 15)); // NOI18N
    IdAfil.setForeground(new java.awt.Color(0, 153, 153));
    IdAfil.setText("ID Afiliado/a:");

    IdAf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        IdAfActionPerformed(evt);
      }
    });

    Nomb.setFont(new java.awt.Font("Bauhaus 93", 0, 15)); // NOI18N
    Nomb.setForeground(new java.awt.Color(0, 153, 153));
    Nomb.setText("Nombre/s:");

    Nom.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        NomActionPerformed(evt);
      }
    });

    Apel.setFont(new java.awt.Font("Bauhaus 93", 0, 15)); // NOI18N
    Apel.setForeground(new java.awt.Color(0, 153, 153));
    Apel.setText("Apellido/s:");

    Ape.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ApeActionPerformed(evt);
      }
    });

    Domi.setFont(new java.awt.Font("Bauhaus 93", 0, 15)); // NOI18N
    Domi.setForeground(new java.awt.Color(0, 153, 153));
    Domi.setText("Domicilio:");

    Dom.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DomActionPerformed(evt);
      }
    });

    Telf.setFont(new java.awt.Font("Bauhaus 93", 0, 15)); // NOI18N
    Telf.setForeground(new java.awt.Color(0, 153, 153));
    Telf.setText("Telf. o Cel. :");

    Ina.setFont(new java.awt.Font("Bauhaus 93", 0, 15)); // NOI18N
    Ina.setForeground(new java.awt.Color(0, 153, 153));
    Ina.setLabel("Inactivo");

    Act.setFont(new java.awt.Font("Bauhaus 93", 0, 15)); // NOI18N
    Act.setForeground(new java.awt.Color(0, 153, 153));
    Act.setLabel("Activo");

    Corre1.setFont(new java.awt.Font("Bauhaus 93", 0, 15)); // NOI18N
    Corre1.setForeground(new java.awt.Color(0, 153, 153));
    Corre1.setText("Estado:");

    Tel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TelActionPerformed(evt);
      }
    });

    Buscar.setBackground(new java.awt.Color(0, 204, 204));
    Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/buscar.png"))); // NOI18N
    Buscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BuscarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout FOrdLayout = new javax.swing.GroupLayout(FOrd);
    FOrd.setLayout(FOrdLayout);
    FOrdLayout.setHorizontalGroup(
      FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FOrdLayout.createSequentialGroup()
        .addComponent(Ordenes)
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(FOrdLayout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(FOrdLayout.createSequentialGroup()
            .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(FOrdLayout.createSequentialGroup()
                .addComponent(Apel)
                .addGap(6, 6, 6)
                .addComponent(Ape, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(FOrdLayout.createSequentialGroup()
                .addComponent(IdAfil)
                .addGap(6, 6, 6)
                .addComponent(IdAf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(FOrdLayout.createSequentialGroup()
                .addComponent(Nomb)
                .addGap(6, 6, 6)
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(35, 35, 35)
            .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(FOrdLayout.createSequentialGroup()
                .addComponent(Corre1)
                .addGap(23, 23, 23)
                .addComponent(Act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(FOrdLayout.createSequentialGroup()
                .addComponent(Domi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(FOrdLayout.createSequentialGroup()
                .addComponent(Telf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tel))))
          .addGroup(FOrdLayout.createSequentialGroup()
            .addComponent(Docu)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(253, Short.MAX_VALUE))
    );
    FOrdLayout.setVerticalGroup(
      FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FOrdLayout.createSequentialGroup()
        .addComponent(Ordenes)
        .addGap(19, 19, 19)
        .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(Docu)
            .addComponent(Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(FOrdLayout.createSequentialGroup()
            .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(FOrdLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(IdAfil))
              .addComponent(IdAf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(FOrdLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(Nomb))
              .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(Apel)
              .addComponent(Ape, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(FOrdLayout.createSequentialGroup()
            .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(Domi)
              .addComponent(Dom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(Telf))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(Corre1)
              .addComponent(Act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(Ina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(566, 566, 566))
    );

    PanelOt.add(FOrd);

    afili.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/afil (1).png"))); // NOI18N
    afili.setText("AFILIADO");

    javax.swing.GroupLayout FAfiLayout = new javax.swing.GroupLayout(FAfi);
    FAfi.setLayout(FAfiLayout);
    FAfiLayout.setHorizontalGroup(
      FAfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FAfiLayout.createSequentialGroup()
        .addComponent(afili, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 676, Short.MAX_VALUE))
    );
    FAfiLayout.setVerticalGroup(
      FAfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FAfiLayout.createSequentialGroup()
        .addComponent(afili, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 735, Short.MAX_VALUE))
    );

    PanelOt.add(FAfi);

    prest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/prestador (1).png"))); // NOI18N

    javax.swing.GroupLayout FPresLayout = new javax.swing.GroupLayout(FPres);
    FPres.setLayout(FPresLayout);
    FPresLayout.setHorizontalGroup(
      FPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FPresLayout.createSequentialGroup()
        .addComponent(prest)
        .addGap(0, 675, Short.MAX_VALUE))
    );
    FPresLayout.setVerticalGroup(
      FPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FPresLayout.createSequentialGroup()
        .addComponent(prest)
        .addGap(0, 737, Short.MAX_VALUE))
    );

    PanelOt.add(FPres);

    espe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/espe (1).png"))); // NOI18N
    espe.setText("ESPECIALISTA");

    javax.swing.GroupLayout FEspLayout = new javax.swing.GroupLayout(FEsp);
    FEsp.setLayout(FEspLayout);
    FEspLayout.setHorizontalGroup(
      FEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FEspLayout.createSequentialGroup()
        .addComponent(espe, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 676, Short.MAX_VALUE))
    );
    FEspLayout.setVerticalGroup(
      FEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FEspLayout.createSequentialGroup()
        .addComponent(espe)
        .addGap(0, 737, Short.MAX_VALUE))
    );

    PanelOt.add(FEsp);

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/emple (1).png"))); // NOI18N
    jLabel6.setText("EMPLEADO");

    javax.swing.GroupLayout FEmpLayout = new javax.swing.GroupLayout(FEmp);
    FEmp.setLayout(FEmpLayout);
    FEmpLayout.setHorizontalGroup(
      FEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FEmpLayout.createSequentialGroup()
        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 676, Short.MAX_VALUE))
    );
    FEmpLayout.setVerticalGroup(
      FEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FEmpLayout.createSequentialGroup()
        .addComponent(jLabel6)
        .addGap(0, 737, Short.MAX_VALUE))
    );

    PanelOt.add(FEmp);

    jDesktopPane1.add(PanelOt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 780));

    getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 780));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TelActionPerformed

  private void DomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_DomActionPerformed

  private void ApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ApeActionPerformed

  private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_NomActionPerformed

  private void DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_DocActionPerformed

  private void IdAfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdAfActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_IdAfActionPerformed

  private void PEmplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PEmplMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(false);
    FAfi.setVisible(false);
    FPres.setVisible(false);
    FEsp.setVisible(false);
    FEmp.setVisible(true);
    Empl.setForeground(new Color(0, 204, 204));
     Espe.setForeground(new Color(204, 102, 0));
     Prest.setForeground(new Color(204, 102, 0));
    Afil.setForeground(new Color(204, 102, 0));
    Orden.setForeground(new Color(204, 102, 0));   
       
    
    
    
    POrden.setBackground(new Color(0, 204, 204));
    PAfil.setBackground(new Color(0, 204, 204));
    PPrest.setBackground(new Color(0, 204, 204));
    PEspe.setBackground(new Color(0, 204, 204));
    PEmpl.setBackground(new Color(204, 102, 0));
  }//GEN-LAST:event_PEmplMouseClicked

  private void PEspeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PEspeMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(false);
    FAfi.setVisible(false);
    FPres.setVisible(false);
    FEsp.setVisible(true);
    FEmp.setVisible(false);
    Espe.setForeground(new Color(0, 204, 204));
     Prest.setForeground(new Color(204, 102, 0));
    Afil.setForeground(new Color(204, 102, 0));
    Orden.setForeground(new Color(204, 102, 0));   
       Empl.setForeground(new Color(204, 102, 0));
    
    
    
    
    
    POrden.setBackground(new Color(0, 204, 204));
    PAfil.setBackground(new Color(0, 204, 204));
    PPrest.setBackground(new Color(0, 204, 204));
    PEspe.setBackground(new Color(204, 102, 0));
    PEmpl.setBackground(new Color(0, 204, 204));
  }//GEN-LAST:event_PEspeMouseClicked

  private void PPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPrestMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(false);
    FAfi.setVisible(false);
    FPres.setVisible(true);
    FEsp.setVisible(false);
    FEmp.setVisible(false);
    
    Prest.setForeground(new Color(0, 204, 204));
    Afil.setForeground(new Color(204, 102, 0));
    Orden.setForeground(new Color(204, 102, 0));   
    Espe.setForeground(new Color(204, 102, 0));
    Empl.setForeground(new Color(204, 102, 0));
    
    POrden.setBackground(new Color(0, 204, 204));
    PAfil.setBackground(new Color(0, 204, 204));
    PPrest.setBackground(new Color(204, 102, 0));
    PEspe.setBackground(new Color(0, 204, 204));
    PEmpl.setBackground(new Color(0, 204, 204));
  }//GEN-LAST:event_PPrestMouseClicked

  private void PAfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAfilMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(false);
    FAfi.setVisible(true);
    FPres.setVisible(false);
    FEsp.setVisible(false);
    FEmp.setVisible(false);
    Afil.setForeground(new Color(0, 204, 204));
    Orden.setForeground(new Color(204, 102, 0));   
    Prest.setForeground(new Color(204, 102, 0));
    Espe.setForeground(new Color(204, 102, 0));
    Empl.setForeground(new Color(204, 102, 0));
    
    
    
    POrden.setBackground(new Color(0, 204, 204));
    PAfil.setBackground(new Color(204, 102, 0));
    PPrest.setBackground(new Color(0, 204, 204));
    PEspe.setBackground(new Color(0, 204, 204));
    PEmpl.setBackground(new Color(0, 204, 204));

  }//GEN-LAST:event_PAfilMouseClicked

  private void POrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POrdenMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(true);
    FAfi.setVisible(false);
    FPres.setVisible(false);
    FEsp.setVisible(false);
    FEmp.setVisible(false);
    Orden.setForeground(new Color(0, 204, 204));
    Afil.setForeground(new Color(204, 102, 0));
    Prest.setForeground(new Color(204, 102, 0));
    Espe.setForeground(new Color(204, 102, 0));
    Empl.setForeground(new Color(204, 102, 0));
    POrden.setBackground(new Color(204, 102, 0));
    PAfil.setBackground(new Color(0, 204, 204));
    PPrest.setBackground(new Color(0, 204, 204));
    PEspe.setBackground(new Color(0, 204, 204));
    PEmpl.setBackground(new Color(0, 204, 204));
  }//GEN-LAST:event_POrdenMouseClicked

  private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
    // TODO add your handling code here:
    try {

      Integer dni = Integer.parseInt(Doc.getText());
      afiliadoActualDni = afiData.buscarAfiliadoPorDni(dni);
      if (afiliadoActualDni != null) {
        Nom.setText(afiliadoActualDni.getNombre());
        Ape.setText(afiliadoActualDni.getApellido());
        IdAf.setText(Integer.toString(afiliadoActualDni.getIdafiliaado()));
        Dom.setText(afiliadoActualDni.getDomicilio());
        Tel.setText(Integer.toString(afiliadoActualDni.getTelefono()));

        if (afiliadoActualDni.isEstado() == true) {
          Act.setState(true);
          Ina.setState(false);
        } else {
          Ina.setState(true);
          Act.setState(false);
        }
      }
    } catch (NumberFormatException ex) {
      JOptionPane.showMessageDialog(this, "Ingrese DNI de Afiliado Válido");
    }
  }//GEN-LAST:event_BuscarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Menu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Checkbox Act;
  private javax.swing.JLabel Afil;
  private javax.swing.JTextField Ape;
  private javax.swing.JLabel Apel;
  private javax.swing.JButton Buscar;
  private javax.swing.JLabel Corre1;
  private javax.swing.JTextField Doc;
  private javax.swing.JLabel Docu;
  private javax.swing.JTextField Dom;
  private javax.swing.JLabel Domi;
  private javax.swing.JLabel Empl;
  private javax.swing.JLabel Espe;
  private javax.swing.JPanel FAfi;
  private javax.swing.JPanel FEmp;
  private javax.swing.JPanel FEsp;
  private javax.swing.JPanel FOrd;
  private javax.swing.JPanel FPres;
  private javax.swing.JTextField IdAf;
  private javax.swing.JLabel IdAfil;
  private java.awt.Checkbox Ina;
  private javax.swing.JTextField Nom;
  private javax.swing.JLabel Nomb;
  private javax.swing.JLabel Orden;
  private javax.swing.JLabel Ordenes;
  private javax.swing.JPanel PAfil;
  private javax.swing.JPanel PEmpl;
  private javax.swing.JPanel PEspe;
  private javax.swing.JPanel POrden;
  private javax.swing.JPanel PPrest;
  private javax.swing.JPanel PanelMenu;
  private javax.swing.JPanel PanelOt;
  private javax.swing.JLabel Prest;
  private javax.swing.JTextField Tel;
  private javax.swing.JLabel Telf;
  private javax.swing.JLabel afili;
  private javax.swing.JLabel espe;
  private javax.swing.JDesktopPane jDesktopPane1;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel logomenu;
  private javax.swing.JLabel prest;
  // End of variables declaration//GEN-END:variables
}
