/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package massalud.Vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JCheckBox;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import massalud.AccesoDatos.AfiliadoData;
import massalud.Entidades.Afiliado;

/**
 *
 * @author Cintia
 */
public class Menu extends javax.swing.JFrame {
private AfiliadoData afiData= new AfiliadoData();
private Afiliado afiliadoActualDni=null;
private Afiliado  afiliadoActualId=null;

  /**
   * Creates new form Menu
   */
  public Menu() {
    initComponents();
setIconImage(new ImageIcon(getClass().getResource("/massalud/Recursos/icon.jpeg")).getImage());    
    setLocationRelativeTo(null);   
//   setIconImage(new ImageIcon(getClass().getResource("/massalud/Recursos/icon.jpeg")).getImage());
     POrden.setBackground( Color.lightGray);     
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jDesktopPane1 = new javax.swing.JDesktopPane();
    ImageIcon icono2=new ImageIcon(getClass().getResource("/massalud/Recursos/f2.jpg"));
    Image imagen2=icono2.getImage();
    PanelMenu = new javax.swing.JPanel(){
      public void paintComponent(Graphics g){
        g.drawImage(imagen2,0,0,getWidth(),getHeight(),this);
      }
    };
    jLabel1 = new javax.swing.JLabel();
    POrden = new javax.swing.JPanel();
    Orden = new javax.swing.JLabel();
    PAfil = new javax.swing.JPanel();
    Afil = new javax.swing.JLabel();
    PPrest = new javax.swing.JPanel();
    Prest = new javax.swing.JLabel();
    PEspe = new javax.swing.JPanel();
    Espe = new javax.swing.JLabel();
    PEmpl = new javax.swing.JPanel();
    Empl = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    PanelOt = new javax.swing.JPanel();
    ImageIcon icono=new ImageIcon(getClass().getResource("/massalud/Recursos/f1.jpg"));
    Image imagen=icono.getImage();
    FOrd = new javax.swing.JPanel(){
      public void paintComponent(Graphics g){
        g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
      }
    };
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    Nomb = new javax.swing.JLabel();
    Nom = new javax.swing.JTextField();
    Apel = new javax.swing.JLabel();
    Ape = new javax.swing.JTextField();
    Sep = new javax.swing.JSeparator();
    Docu = new javax.swing.JLabel();
    Doc = new javax.swing.JTextField();
    Domi = new javax.swing.JLabel();
    Dom = new javax.swing.JTextField();
    Telf = new javax.swing.JLabel();
    Tel = new javax.swing.JTextField();
    Corre = new javax.swing.JLabel();
    Cor = new javax.swing.JTextField();
    Corre1 = new javax.swing.JLabel();
    label1 = new java.awt.Label();
    IdAf = new javax.swing.JTextField();
    IdAfil = new javax.swing.JLabel();
    BBusc = new java.awt.Button();
    Act = new java.awt.Checkbox();
    Ina = new java.awt.Checkbox();
    IdEmp = new java.awt.Label();
    IdEm = new javax.swing.JTextField();
    FAfi = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    FPres = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    FEsp = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    FEmp = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/Recursos/log.gif"))); // NOI18N

    POrden.setBackground(new java.awt.Color(102, 255, 255));
    POrden.setPreferredSize(new java.awt.Dimension(280, 50));
    POrden.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        POrdenMouseClicked(evt);
      }
    });

    Orden.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    Orden.setForeground(new java.awt.Color(0, 102, 255));
    Orden.setText("ORDEN");

    javax.swing.GroupLayout POrdenLayout = new javax.swing.GroupLayout(POrden);
    POrden.setLayout(POrdenLayout);
    POrdenLayout.setHorizontalGroup(
      POrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(POrdenLayout.createSequentialGroup()
        .addGap(60, 60, 60)
        .addComponent(Orden)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    POrdenLayout.setVerticalGroup(
      POrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POrdenLayout.createSequentialGroup()
        .addComponent(Orden, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        .addContainerGap())
    );

    PAfil.setBackground(new java.awt.Color(51, 255, 255));
    PAfil.setPreferredSize(new java.awt.Dimension(280, 50));
    PAfil.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        PAfilMouseClicked(evt);
      }
    });

    Afil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    Afil.setForeground(new java.awt.Color(51, 102, 255));
    Afil.setText("AFILIADO");

    javax.swing.GroupLayout PAfilLayout = new javax.swing.GroupLayout(PAfil);
    PAfil.setLayout(PAfilLayout);
    PAfilLayout.setHorizontalGroup(
      PAfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PAfilLayout.createSequentialGroup()
        .addGap(62, 62, 62)
        .addComponent(Afil)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    PAfilLayout.setVerticalGroup(
      PAfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Afil, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
    );

    PPrest.setBackground(new java.awt.Color(51, 255, 255));
    PPrest.setForeground(new java.awt.Color(51, 51, 255));
    PPrest.setPreferredSize(new java.awt.Dimension(280, 50));
    PPrest.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        PPrestMouseClicked(evt);
      }
    });

    Prest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    Prest.setForeground(new java.awt.Color(51, 102, 255));
    Prest.setText("PRESTADOR");

    javax.swing.GroupLayout PPrestLayout = new javax.swing.GroupLayout(PPrest);
    PPrest.setLayout(PPrestLayout);
    PPrestLayout.setHorizontalGroup(
      PPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PPrestLayout.createSequentialGroup()
        .addGap(62, 62, 62)
        .addComponent(Prest)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    PPrestLayout.setVerticalGroup(
      PPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Prest, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
    );

    PEspe.setBackground(new java.awt.Color(51, 255, 255));
    PEspe.setForeground(new java.awt.Color(51, 102, 255));
    PEspe.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        PEspeMouseClicked(evt);
      }
    });

    Espe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    Espe.setForeground(new java.awt.Color(51, 102, 255));
    Espe.setText("ESPECIALIDAD");

    javax.swing.GroupLayout PEspeLayout = new javax.swing.GroupLayout(PEspe);
    PEspe.setLayout(PEspeLayout);
    PEspeLayout.setHorizontalGroup(
      PEspeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PEspeLayout.createSequentialGroup()
        .addGap(62, 62, 62)
        .addComponent(Espe)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    PEspeLayout.setVerticalGroup(
      PEspeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Espe, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
    );

    PEmpl.setBackground(new java.awt.Color(51, 255, 255));
    PEmpl.setForeground(new java.awt.Color(51, 102, 255));
    PEmpl.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        PEmplMouseClicked(evt);
      }
    });

    Empl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    Empl.setForeground(new java.awt.Color(51, 51, 255));
    Empl.setText("EMPLEADOS");

    javax.swing.GroupLayout PEmplLayout = new javax.swing.GroupLayout(PEmpl);
    PEmpl.setLayout(PEmplLayout);
    PEmplLayout.setHorizontalGroup(
      PEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PEmplLayout.createSequentialGroup()
        .addGap(62, 62, 62)
        .addComponent(Empl)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    PEmplLayout.setVerticalGroup(
      PEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Empl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
    PanelMenu.setLayout(PanelMenuLayout);
    PanelMenuLayout.setHorizontalGroup(
      PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(PEmpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(PEspe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(PPrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(PAfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(POrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel7)
        .addGap(68, 68, 68))
      .addGroup(PanelMenuLayout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    PanelMenuLayout.setVerticalGroup(
      PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PanelMenuLayout.createSequentialGroup()
        .addGap(84, 84, 84)
        .addComponent(jLabel7)
        .addGap(18, 18, 18)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(93, 93, 93)
        .addComponent(POrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(PAfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(PPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(PEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(PEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(140, Short.MAX_VALUE))
    );

    jDesktopPane1.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 280, 780));

    PanelOt.setBackground(new java.awt.Color(204, 255, 204));
    PanelOt.setLayout(new javax.swing.OverlayLayout(PanelOt));

    FOrd.setPreferredSize(new java.awt.Dimension(860, 780));

    jPanel1.setBackground(new java.awt.Color(153, 255, 255));

    jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 102, 255));
    jLabel2.setText("ORDEN");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addComponent(jLabel2)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2)
        .addContainerGap(13, Short.MAX_VALUE))
    );

    jPanel3.setBackground(new java.awt.Color(204, 204, 204));
    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Afiliado/a:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 102, 204))); // NOI18N
    jPanel3.setForeground(new java.awt.Color(0, 102, 255));

    Nomb.setForeground(new java.awt.Color(0, 102, 204));
    Nomb.setText("Nombre/s:");

    Nom.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        NomActionPerformed(evt);
      }
    });

    Apel.setForeground(new java.awt.Color(0, 102, 204));
    Apel.setText("Apellido/s:");

    Ape.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ApeActionPerformed(evt);
      }
    });

    Sep.setBackground(new java.awt.Color(153, 255, 255));
    Sep.setForeground(new java.awt.Color(153, 255, 255));
    Sep.setOrientation(javax.swing.SwingConstants.VERTICAL);

    Docu.setForeground(new java.awt.Color(0, 102, 204));
    Docu.setText("DNI:");

    Doc.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DocActionPerformed(evt);
      }
    });

    Domi.setForeground(new java.awt.Color(0, 102, 204));
    Domi.setText("Domicilio:");

    Dom.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DomActionPerformed(evt);
      }
    });

    Telf.setForeground(new java.awt.Color(0, 102, 204));
    Telf.setText("Telf. o Cel. :");

    Tel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TelActionPerformed(evt);
      }
    });

    Corre.setForeground(new java.awt.Color(0, 102, 204));
    Corre.setText("E-mail:");

    Cor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        CorActionPerformed(evt);
      }
    });

    Corre1.setForeground(new java.awt.Color(0, 102, 204));
    Corre1.setText("Estado:");

    label1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
    label1.setForeground(new java.awt.Color(0, 51, 153));
    label1.setText("o");

    IdAf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        IdAfActionPerformed(evt);
      }
    });

    IdAfil.setForeground(new java.awt.Color(0, 102, 204));
    IdAfil.setText("ID Afiliado/a:");

    BBusc.setFont(new java.awt.Font("Dialog", 3, 20)); // NOI18N
    BBusc.setForeground(new java.awt.Color(0, 51, 255));
    BBusc.setLabel("BUSCAR");
    BBusc.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BBuscActionPerformed(evt);
      }
    });
    BBusc.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        BBuscKeyPressed(evt);
      }
    });

    Act.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
    Act.setForeground(new java.awt.Color(0, 102, 255));
    Act.setLabel("Activo");

    Ina.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
    Ina.setForeground(new java.awt.Color(0, 51, 255));
    Ina.setLabel("Inacivo");

    IdEmp.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
    IdEmp.setForeground(new java.awt.Color(0, 102, 204));
    IdEmp.setText(" Empleado");

    IdEm.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        IdEmActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addComponent(Nomb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(Apel)
                  .addComponent(Corre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(Act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(Ina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(Ape))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Sep, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Domi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dom))
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Corre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Telf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addComponent(Docu)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(IdAfil)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(IdAf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(BBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(IdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(IdEm, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(BBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Docu)
                .addComponent(Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(IdAfil)
                .addComponent(IdAf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(IdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(IdEm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(20, 20, 20)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(Domi)
              .addComponent(Dom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(Corre)
              .addComponent(Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(Telf)
              .addComponent(Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(143, 143, 143))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(Nomb)
              .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(Apel)
              .addComponent(Ape, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(Corre1)
              .addComponent(Act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(Ina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(22, 22, 22))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(Sep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))))
    );

    javax.swing.GroupLayout FOrdLayout = new javax.swing.GroupLayout(FOrd);
    FOrd.setLayout(FOrdLayout);
    FOrdLayout.setHorizontalGroup(
      FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FOrdLayout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(FOrdLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    FOrdLayout.setVerticalGroup(
      FOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FOrdLayout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(535, Short.MAX_VALUE))
    );

    PanelOt.add(FOrd);

    jLabel3.setText("AFILIADO");

    javax.swing.GroupLayout FAfiLayout = new javax.swing.GroupLayout(FAfi);
    FAfi.setLayout(FAfiLayout);
    FAfiLayout.setHorizontalGroup(
      FAfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FAfiLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel3)
        .addGap(191, 191, 191))
    );
    FAfiLayout.setVerticalGroup(
      FAfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FAfiLayout.createSequentialGroup()
        .addGap(86, 86, 86)
        .addComponent(jLabel3)
        .addContainerGap(673, Short.MAX_VALUE))
    );

    PanelOt.add(FAfi);

    jLabel4.setText("PRESTADOR");

    javax.swing.GroupLayout FPresLayout = new javax.swing.GroupLayout(FPres);
    FPres.setLayout(FPresLayout);
    FPresLayout.setHorizontalGroup(
      FPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FPresLayout.createSequentialGroup()
        .addGap(238, 238, 238)
        .addComponent(jLabel4)
        .addContainerGap(540, Short.MAX_VALUE))
    );
    FPresLayout.setVerticalGroup(
      FPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FPresLayout.createSequentialGroup()
        .addGap(308, 308, 308)
        .addComponent(jLabel4)
        .addContainerGap(451, Short.MAX_VALUE))
    );

    PanelOt.add(FPres);

    jLabel5.setText("ESPECIALISTA");

    javax.swing.GroupLayout FEspLayout = new javax.swing.GroupLayout(FEsp);
    FEsp.setLayout(FEspLayout);
    FEspLayout.setHorizontalGroup(
      FEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 860, Short.MAX_VALUE)
      .addGroup(FEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(FEspLayout.createSequentialGroup()
          .addGap(233, 233, 233)
          .addComponent(jLabel5)
          .addContainerGap(535, Short.MAX_VALUE)))
    );
    FEspLayout.setVerticalGroup(
      FEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 780, Short.MAX_VALUE)
      .addGroup(FEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(FEspLayout.createSequentialGroup()
          .addGap(308, 308, 308)
          .addComponent(jLabel5)
          .addContainerGap(451, Short.MAX_VALUE)))
    );

    PanelOt.add(FEsp);

    jLabel6.setText("EMPLEADO");

    javax.swing.GroupLayout FEmpLayout = new javax.swing.GroupLayout(FEmp);
    FEmp.setLayout(FEmpLayout);
    FEmpLayout.setHorizontalGroup(
      FEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 860, Short.MAX_VALUE)
      .addGroup(FEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(FEmpLayout.createSequentialGroup()
          .addGap(241, 241, 241)
          .addComponent(jLabel6)
          .addContainerGap(543, Short.MAX_VALUE)))
    );
    FEmpLayout.setVerticalGroup(
      FEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 780, Short.MAX_VALUE)
      .addGroup(FEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(FEmpLayout.createSequentialGroup()
          .addGap(308, 308, 308)
          .addComponent(jLabel6)
          .addContainerGap(451, Short.MAX_VALUE)))
    );

    PanelOt.add(FEmp);

    jDesktopPane1.add(PanelOt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 780));

    getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 780));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void POrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POrdenMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(true);
    FAfi.setVisible(false);
    FPres.setVisible(false);
    FEsp.setVisible(false);
    FEmp.setVisible(false);
    POrden.setBackground( Color.lightGray);
    PAfil.setBackground(new Color(102,255,255));
    PPrest.setBackground(new Color(102,255,255));
    PEspe.setBackground(new Color(102,255,255));
    PEmpl.setBackground(new Color(102,255,255));
  }//GEN-LAST:event_POrdenMouseClicked

  private void PAfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAfilMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(false);
    FAfi.setVisible(true);
    FPres.setVisible(false);
    FEsp.setVisible(false);
    FEmp.setVisible(false);
    POrden.setBackground(new Color(102, 255, 255));
    PAfil.setBackground(Color.lightGray);
    PPrest.setBackground(new Color(102, 255, 255));
    PEspe.setBackground(new Color(102, 255, 255));
    PEmpl.setBackground(new Color(102, 255, 255));
    
    
    
  }//GEN-LAST:event_PAfilMouseClicked

  private void PPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPrestMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(false);
    FAfi.setVisible(false);
    FPres.setVisible(true);
    FEsp.setVisible(false);
    FEmp.setVisible(false);
    POrden.setBackground(new Color(102, 255, 255));
    PAfil.setBackground(new Color(102, 255, 255));
    PPrest.setBackground(Color.lightGray);
    PEspe.setBackground(new Color(102, 255, 255));
    PEmpl.setBackground(new Color(102, 255, 255));
  }//GEN-LAST:event_PPrestMouseClicked

  private void PEspeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PEspeMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(false);
    FAfi.setVisible(false);
    FPres.setVisible(false);
    FEsp.setVisible(true);
    FEmp.setVisible(false);
     POrden.setBackground(new Color(102, 255, 255));
    PAfil.setBackground(new Color(102, 255, 255));
    PPrest.setBackground(new Color(102, 255, 255));
    PEspe.setBackground(Color.lightGray);
    PEmpl.setBackground(new Color(102, 255, 255));
  }//GEN-LAST:event_PEspeMouseClicked

  private void PEmplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PEmplMouseClicked
    // TODO add your handling code here:
    FOrd.setVisible(false);
    FAfi.setVisible(false);
    FPres.setVisible(false);
    FEsp.setVisible(false);
    FEmp.setVisible(true);
     POrden.setBackground(new Color(102, 255, 255));
    PAfil.setBackground(new Color(102, 255, 255));
    PPrest.setBackground(new Color(102, 255, 255));
    PEspe.setBackground(new Color(102, 255, 255));
    PEmpl.setBackground(Color.lightGray);
  }//GEN-LAST:event_PEmplMouseClicked

  private void TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TelActionPerformed

  private void DomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_DomActionPerformed

  private void ApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ApeActionPerformed

  private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_NomActionPerformed

  private void DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_DocActionPerformed

  private void CorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_CorActionPerformed

  private void IdAfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdAfActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_IdAfActionPerformed

  private void IdEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdEmActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_IdEmActionPerformed

  private void BBuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscActionPerformed
    // TODO add your handling code here:
    try{
      Integer dni= Integer.parseInt(Doc.getText());
////      Integer id= Integer.parseInt(IdAfil.getText());
      afiliadoActualDni=afiData.buscarAfiliadoPorDni(dni);
//      afiliadoActualId=afiData.buscarAfiliado(id);
      if(afiliadoActualDni!=null){
//      IdEm.setText(afiliadoActualDni.getIdEmpleado(get.empleado));
      Nom.setText(afiliadoActualDni.getNombre());
      Ape.setText(afiliadoActualDni.getApellido());
      IdAf.setText(Integer.toString(afiliadoActualDni.getIdafiliaado()));
      Dom.setText(afiliadoActualDni.getDomicilio());
      Tel.setText(Integer.toString(afiliadoActualDni.getTelefono()));
   
   
// if (afiliadoActualDni.isEstado() == true) {
//
//Act.setSelected(afiData.getEstado());
//
//} else {
//
//Ina.setSelected(afiData.isEstado());
//
//}
     
      }
    }catch(NumberFormatException ex){
      JOptionPane.showMessageDialog(this, "Ingrese DNI o Id de Afiliado Válido");
    }
    
  }//GEN-LAST:event_BBuscActionPerformed

  private void BBuscKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BBuscKeyPressed
    // TODO add your handling code here:
  }//GEN-LAST:event_BBuscKeyPressed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {        
        new Menu().setVisible(true);        
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Checkbox Act;
  private javax.swing.JLabel Afil;
  private javax.swing.JTextField Ape;
  private javax.swing.JLabel Apel;
  private java.awt.Button BBusc;
  private javax.swing.JTextField Cor;
  private javax.swing.JLabel Corre;
  private javax.swing.JLabel Corre1;
  private javax.swing.JTextField Doc;
  private javax.swing.JLabel Docu;
  private javax.swing.JTextField Dom;
  private javax.swing.JLabel Domi;
  private javax.swing.JLabel Empl;
  private javax.swing.JLabel Espe;
  private javax.swing.JPanel FAfi;
  private javax.swing.JPanel FEmp;
  private javax.swing.JPanel FEsp;
  private javax.swing.JPanel FOrd;
  private javax.swing.JPanel FPres;
  private javax.swing.JTextField IdAf;
  private javax.swing.JLabel IdAfil;
  private javax.swing.JTextField IdEm;
  private java.awt.Label IdEmp;
  private java.awt.Checkbox Ina;
  private javax.swing.JTextField Nom;
  private javax.swing.JLabel Nomb;
  private javax.swing.JLabel Orden;
  private javax.swing.JPanel PAfil;
  private javax.swing.JPanel PEmpl;
  private javax.swing.JPanel PEspe;
  private javax.swing.JPanel POrden;
  private javax.swing.JPanel PPrest;
  private javax.swing.JPanel PanelMenu;
  private javax.swing.JPanel PanelOt;
  private javax.swing.JLabel Prest;
  private javax.swing.JSeparator Sep;
  private javax.swing.JTextField Tel;
  private javax.swing.JLabel Telf;
  private javax.swing.JDesktopPane jDesktopPane1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private java.awt.Label label1;
  // End of variables declaration//GEN-END:variables
}
